server:
  image: node:7
  command: npm run backend
  working_dir: /app
  volumes:
    - ./server:/app
  environment:
    PORT: 3000
  ports:
    - "3000:3000"
  links:
    - mongodb

frontend:
  image: node:7
  command: npm run webpack
  working_dir: /app/frontend/
  volumes:
    - ./frontend:/app/frontend/
    - ./public:/app/public
  ports:
    - "4000:4000"

public:
  image: nginx
  ports:
      - "8080:8080"
  volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html

mongodb:
  image: mongo
  ports:
      - "27017:27017"
